const dummyData = [
  {
    id: 1,
    postedOn: "2024-04-30",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2024-04-24",
    title: "Frontend Developer",
    type: "Full time",
    location: "In-office",
    experience: "Fresher",
    company: "Amazon",
    skills: ["Javascript", "Nextjs", "Tailwind CSS"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: "2024-04-27",
    title: "Android Developer",
    type: "Part time",
    location: "Remote",
    experience: "Senior Level",
    company: "Facebook",
    skills: ["Kotlin", "MVVM"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 4,
    postedOn: "2024-04-26",
    title: "Developer Advocate",
    type: "Contract",
    location: "Hybrid",
    experience: "Junior Level",
    company: "Netflix",
    companyUrl: "https://facebook.com",
    skills: ["web3", "Content Creation", "Community"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    id: 5,
    postedOn: "2024-04-02",
    title: "Software Engineer",
    type: "Full Time",
    location: "In-office",
    experience: "Senior Level",
    company: "Microsoft",
    skills: ["Java", "Spring Boot", "Microservices"],
    job_link: "https://careers.microsoft.com/",
  },
  {
    id: 6,
    postedOn: "2024-04-05",
    title: "UI/UX Designer",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Google",
    skills: ["Adobe XD", "Figma", "User Research"],
    job_link: "https://careers.google.com/",
  },
  {
    id: 7,
    postedOn: "2024-04-08",
    title: "Data Analyst",
    type: "Part Time",
    location: "Hybrid",
    experience: "Junior Level",
    company: "Amazon",
    skills: ["SQL", "Tableau", "Data Visualization"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 8,
    postedOn: "2024-04-10",
    title: "Backend Engineer",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Facebook",
    skills: ["Node.js", "Express", "MongoDB"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 9,
    postedOn: "2024-4-12",
    title: "Product Manager",
    type: "Full Time",
    location: "In-office",
    experience: "Senior Level",
    company: "Apple",
    skills: ["Product Strategy", "Market Research", "Project Management"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 10,
    postedOn: "2024-04-15",
    title: "Quality Assurance Engineer",
    type: "Contract",
    location: "Hybrid",
    experience: "Junior Level",
    company: "Google",
    skills: ["Manual Testing", "Automation Testing", "Bug Tracking"],
    job_link: "https://careers.google.com/",
  },
  // Additional entries
  {
    id: 11,
    postedOn: "2024-04-20",
    title: "DevOps Engineer",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Amazon",
    skills: ["Docker", "Kubernetes", "CI/CD"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 12,
    postedOn: "2024-04-25",
    title: "Machine Learning Engineer",
    type: "Full Time",
    location: "In-office",
    experience: "Senior Level",
    company: "Microsoft",
    skills: ["Python", "TensorFlow", "Deep Learning"],
    job_link: "https://careers.microsoft.com/",
  },
  {
    id: 13,
    postedOn: "2024-04-28",
    title: "Cloud Architect",
    type: "Part Time",
    location: "Hybrid",
    experience: "Junior Level",
    company: "Google",
    skills: ["AWS", "Azure", "GCP"],
    job_link: "https://careers.google.com/",
  },
  {
    id: 14,
    postedOn: "2024-04-02",
    title: "Cybersecurity Analyst",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Facebook",
    skills: ["Cyber Threat Intelligence", "SIEM", "Penetration Testing"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 15,
    postedOn: "2024-04-05",
    title: "Product Designer",
    type: "Full Time",
    location: "In-office",
    experience: "Junior Level",
    company: "Apple",
    skills: ["Sketch", "Adobe Creative Suite", "User Experience Design"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 16,
    postedOn: "2024-04-08",
    title: "Data Scientist",
    type: "Part Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Netflix",
    skills: ["Python", "R", "Machine Learning"],
    job_link: "https://jobs.netflix.com/",
  },
  {
    id: 17,
    postedOn: "2024-04-12",
    title: "Backend Developer",
    type: "Full Time",
    location: "In-office",
    experience: "Senior Level",
    company: "Amazon",
    skills: ["Java", "Spring Boot", "Microservices"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 18,
    postedOn: "2024-04-15",
    title: "UI Developer",
    type: "Full Time",
    location: "Remote",
    experience: "Fresher",
    company: "Google",
    skills: ["HTML", "CSS", "JavaScript"],
    job_link: "https://careers.google.com/",
  },
  {
    id: 19,
    postedOn: "2024-04-18",
    title: "Product Manager",
    type: "Contract",
    location: "Hybrid",
    experience: "Senior Level",
    company: "Facebook",
    skills: ["Product Strategy", "Market Research", "Project Management"],
    job_link: "https://facebook.com/careers",
  },
  {
    id: 20,
    postedOn: "2024-04-22",
    title: "Software Engineer",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Microsoft",
    skills: ["Java", "Spring Boot", "Microservices"],
    job_link: "https://careers.microsoft.com/",
  },
  // Add more entries as needed
];

export default dummyData;
